{
 "title": "Rspamd",
 "tags": [
  "apps",
  "rspamd"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(rspamd_build_info{job=\"rspamd\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sys Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_connections{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scan time average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_scan_time_average{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_allocated_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Scanned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_scanned_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scanned messages",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_ham_total{instance=\"$instance\"}",
     "legendFormat": "HAM"
    },
    {
     "expr": "rspamd_spam_total{instance=\"$instance\"}",
     "legendFormat": "SPAM"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_chunks_allocated{instance=\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "rspamd_chunks_freed{instance=\"$instance\"}",
     "legendFormat": "Freed"
    },
    {
     "expr": "rspamd_shared_chunks_allocated{instance=\"$instance\"}",
     "legendFormat": "Shared Allocated"
    },
    {
     "expr": "rspamd_chunks_oversized{instance=\"$instance\"}",
     "legendFormat": "Oversized"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_pools_allocated{instance=\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "rspamd_pools_freed{instance=\"$instance\"}",
     "legendFormat": "Freed"
    }
   ]
  },
  {
   "title": "Learn",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_learns_total{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "No action",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_actions_total{instance=\"$instance\",type=\"no action\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Rewrite subject",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_actions_total{instance=\"$instance\",type=\"rewrite subject\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Reject",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_actions_total{instance=\"$instance\",type=\"reject\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Add header",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_actions_total{instance=\"$instance\",type=\"add header\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Greylist",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_actions_total{instance=\"$instance\",type=\"greylist\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Soft Reject",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_actions_total{instance=\"$instance\",type=\"soft reject\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Actions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(rspamd_actions_total{instance=\"$instance\"}[2m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "SPAM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "rate(rspamd_spam_total{instance=\"$instance\"}[2m])",
     "legendFormat": "SPAM"
    },
    {
     "expr": "rate(rspamd_ham_total{instance=\"$instance\"}[2m])",
     "legendFormat": "HAM"
    },
    {
     "expr": "rate(rspamd_scanned_total{instance=\"$instance\"}[2m])",
     "legendFormat": "Scanned"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rspamd_chunks_allocated{instance=\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "rspamd_chunks_freed{instance=\"$instance\"}",
     "legendFormat": "Freed"
    },
    {
     "expr": "rspamd_shared_chunks_allocated{instance=\"$instance\"}",
     "legendFormat": "Shared Allocated"
    },
    {
     "expr": "rspamd_chunks_oversized{instance=\"$instance\"}",
     "legendFormat": "Oversized"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "rspamd_pools_allocated{instance=\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "rspamd_pools_freed{instance=\"$instance\"}",
     "legendFormat": "Freed"
    }
   ]
  }
 ]
}